export const ATIVIDADES_BASE = [
  { id: "remediacao_inst", label: "Instalação de Sistemas de Remediação (MPE, P&T)", short: "Instalação remediação" },
  { id: "remediacao_manut", label: "Manutenção de Sistemas de Remediação (MPE, P&T)", short: "Manutenção remediação" },
  { id: "remediacao_oper", label: "Operação de Sistemas de Remediação (MPE, P&T)", short: "Operação remediação" },
  { id: "desmob_remediacao", label: "Desmobilização de sistemas de remediação", short: "Desmob. remediação" },
  { id: "bailer", label: "Amostragem Volume Determinado (Bailer)", short: "Amostr. bailer" },
  { id: "bx_vazao", label: "Amostragem Baixa Vazão", short: "Amostr. baixa vazão" },
  { id: "multiparam", label: "Leitura e Calibração em campo de Multiparâmetros", short: "Multiparâmetros" },
  { id: "pid", label: "Leitura e Calibração em campo de medidores de Voláteis PID", short: "PID voláteis" },
  { id: "esteira_biosonda", label: "Operação de máquinas de sondagem sobre esteira (Biosonda)", short: "Esteira Biosonda" },
  { id: "esteira_geoprobe", label: "Operação de máquinas de sondagem sobre esteira (Geoprobe)", short: "Esteira Geoprobe" },
  { id: "sond_caminhao", label: "Operação de máquinas de sondagem (caminhão)", short: "Sond. caminhão" },
  { id: "nivel_dagua", label: "Monitoramento de nível d'água em poços", short: "Nível d'água" },
  { id: "poco_monit", label: "Instalação de poços de monitoramento ou de observação", short: "Inst. poços monit." },
  { id: "acabamento_poco", label: "Acabamento de poços de monitoramento", short: "Acabamento de poços" },
  { id: "injecao", label: "Injeção de produtos remediadores (controle de pressão, vazão e parâmetros de injeção)", short: "Injeção remediadores" },
  { id: "injecao_montagem", label: "Montagem de sistema de injeção (bombas, tanques, mistura e controle de parâmetros de injeção como pressão e vazão)", short: "Montagem inj." },
  { id: "topo_rtk", label: "Topografia em campo usando RTK", short: "Topografia RTK" },
  { id: "topo_estacao", label: "Topografia em campo usando Estação Total", short: "Topo. Estação Total" },
  { id: "escavacao", label: "Escavação controlada", short: "Escavação controlada" },
  { id: "desmont_ind", label: "Desmontagem industrial controlada", short: "Desmont. industrial" },
  { id: "soil_mixing", label: "Execução de remediação por Soil Mixing", short: "Soil Mixing" },
  { id: "lab_cromato", label: "Operação de laboratório cromatográfico de campo", short: "Lab. cromatográfico" },
  { id: "colorimetro", label: "Condução de análises com colorímetro em ensaio piloto de oxidação", short: "Colorímetro (piloto)" },
  { id: "raio_influencia", label: "Execução de ensaio piloto para determinação de raio de influência", short: "Ensaio raio influência" },
  { id: "descricao_solo", label: "Amostragem e Descrição de solo durante sondagem conforme normas", short: "Descrição de solo" },
  { id: "tamponamento", label: "Tamponamento de poços", short: "Tamponamento poços" },
  { id: "oip_hpt", label: "Operação de sistema OIP/HPT", short: "OIP/HPT" },
  { id: "mip_hpt", label: "Operação de sistema MIP/HPT", short: "MIP/HPT" },
  { id: "poco_vapor", label: "Instalação de Poços de Vapor Subslab", short: "Poços vapor subslab" },
  { id: "psg", label: "Instalação e Coleta de Amostradores Passivos PSG", short: "Amostradores PSG" },
  { id: "amostr_vapor", label: "Amostragem de Poços de Vapor Subslab", short: "Amostr. vapor subslab" },
  { id: "sond_liner", label: "Sondagem Direct Push Liner Contínuo", short: "DP Liner Contínuo" },
  { id: "sond_dualtube", label: "Sondagem Dual Tube", short: "Dual Tube" },
  { id: "sond_hollow", label: "Sondagem Hollow Auger", short: "Hollow Auger" },
  { id: "sond_injecao", label: "Sondagem para injeção de produtos remediadores", short: "Sond. p/ injeção" },
];
export const ATIVIDADES = [...ATIVIDADES_BASE];
export const ATIV_SINONIMOS = {
  "monitoramento": "nivel_dagua", "nivel": "nivel_dagua", "baixa vazao": "bx_vazao", "low flow": "bx_vazao",
  "bailer": "bailer", "multiparametro": "multiparam", "pid": "pid", "geoprobe": "esteira_geoprobe", "biosonda": "esteira_biosonda",
  "sondagem caminhao": "sond_caminhao", "poco de monitoramento": "poco_monit", "instalacao de poco": "poco_monit",
  "injecao": "injecao", "rtk": "topo_rtk", "estacao total": "topo_estacao", "escavacao": "escavacao",
  "soil mixing": "soil_mixing", "cromatografo": "lab_cromato", "laboratorio": "lab_cromato", "colorimetro": "colorimetro",
  "raio de influencia": "raio_influencia", "teste piloto": "raio_influencia", "descricao de solo": "descricao_solo",
  "tamponamento": "tamponamento", "oip": "oip_hpt", "mip": "mip_hpt", "vapor subslab": "poco_vapor", "subslab": "poco_vapor",
  "psg": "psg", "passivo": "psg", "amostragem de vapor": "amostr_vapor", "remediacao": "remediacao_oper",
  "desmobilizacao": "desmob_remediacao", "desmontagem": "desmont_ind",
};
export const UNID_ATV = {
  remediacao_inst: "sistema(s)", remediacao_manut: "sistema(s)", remediacao_oper: "sistema(s)", acabamento_poco: "poços", bailer: "amostras", bx_vazao: "amostras", multiparam: "pontos", pid: "pontos",
  esteira_biosonda: "metros", esteira_geoprobe: "metros", nivel_dagua: "poços", poco_monit: "poços", sond_caminhao: "metros",
  injecao: "litros", injecao_montagem: "horas", topo_rtk: "pontos", topo_estacao: "pontos", desmob_remediacao: "sistema(s)", escavacao: "m³",
  desmont_ind: "unidade(s)", soil_mixing: "m³", lab_cromato: "amostras", colorimetro: "amostras", raio_influencia: "ensaios",
  descricao_solo: "metros", tamponamento: "poços", oip_hpt: "metros", mip_hpt: "metros", poco_vapor: "poços",
  psg: "amostradores", amostr_vapor: "amostras",
  sond_liner: "metros", sond_dualtube: "metros", sond_hollow: "metros", sond_injecao: "metros",
};
export const PROD_DIA = {
  esteira_biosonda: 20, esteira_geoprobe: 25, sond_caminhao: 20, descricao_solo: 20, oip_hpt: 18, mip_hpt: 18,
  bailer: 8, bx_vazao: 6, nivel_dagua: 20, poco_monit: 4, tamponamento: 5, topo_rtk: 30, topo_estacao: 18,
  multiparam: 12, pid: 12, psg: 10, poco_vapor: 4, amostr_vapor: 10,
  injecao: 2000, injecao_montagem: 8,
  sond_liner: 22, sond_dualtube: 20, sond_hollow: 15, sond_injecao: 18,
  remediacao_inst: 0.2, remediacao_manut: 1, desmob_remediacao: 0.2,
  colorimetro: 8, raio_influencia: 1,
};
export const UNID_PROD = {
  esteira_biosonda: "m/dia", esteira_geoprobe: "m/dia", sond_caminhao: "m/dia",
  oip_hpt: "m/dia", mip_hpt: "m/dia", bailer: "amostras/dia", bx_vazao: "amostras/dia",
  nivel_dagua: "poços/dia", poco_monit: "m/dia", tamponamento: "poços/dia", topo_rtk: "pontos/dia",
  topo_estacao: "pontos/dia", multiparam: "leituras/dia", pid: "leituras/dia", psg: "pontos/dia",
  poco_vapor: "poços/dia", amostr_vapor: "amostras/dia", injecao: "Litros/dia", injecao_montagem: "Horas", remediacao_inst: "Sistema/semana", remediacao_manut: "Sistema/dia", remediacao_oper: "—", acabamento_poco: "poços/dia",
  desmob_remediacao: "Sistema/semana", escavacao: "m³/dia", desmont_ind: "diárias", soil_mixing: "m³/dia",
  lab_cromato: "amostras/dia", colorimetro: "Análises/dia", raio_influencia: "Ensaios/dia",
  descricao_solo: "Amostras/dia",
  sond_liner: "m/dia", sond_dualtube: "m/dia", sond_hollow: "m/dia", sond_injecao: "m/dia",
};
export const PROD_META_PADRAO = { ...PROD_DIA };
