export const UFS = ["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"];
export const CIDADES_POR_UF = {"AC": ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá", "Feijó"], "AL": ["Maceió", "Arapiraca", "Palmeira dos Índios", "Rio Largo", "Penedo", "União dos Palmares"], "AP": ["Macapá", "Santana", "Laranjal do Jari", "Oiapoque", "Mazagão"], "AM": ["Manaus", "Parintins", "Itacoatiara", "Manacapuru", "Coari", "Tabatinga", "Tefé"], "BA": ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Itabuna", "Juazeiro", "Ilhéus", "Lauro de Freitas", "Barreiras", "Porto Seguro", "Simões Filho", "Alagoinhas", "Teixeira de Freitas"], "CE": ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú", "Sobral", "Crato", "Itapipoca", "Maranguape", "Iguatu", "Quixadá"], "DF": ["Brasília", "Ceilândia", "Taguatinga", "Gama", "Sobradinho", "Planaltina"], "ES": ["Vitória", "Vila Velha", "Serra", "Cariacica", "Linhares", "Cachoeiro de Itapemirim", "Colatina", "Guarapari", "São Mateus", "Aracruz"], "GO": ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde", "Luziânia", "Águas Lindas de Goiás", "Valparaíso de Goiás", "Trindade", "Formosa", "Catalão", "Itumbiara"], "MA": ["São Luís", "Imperatriz", "São José de Ribamar", "Timon", "Caxias", "Codó", "Paço do Lumiar", "Açailândia", "Bacabal", "Balsas"], "MT": ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop", "Tangará da Serra", "Cáceres", "Sorriso", "Lucas do Rio Verde", "Primavera do Leste", "Barra do Garças"], "MS": ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá", "Ponta Porã", "Naviraí", "Nova Andradina", "Aquidauana", "Sidrolândia", "Paranaíba"], "MG": ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros", "Ribeirão das Neves", "Uberaba", "Governador Valadares", "Ipatinga", "Sete Lagoas", "Divinópolis", "Santa Luzia", "Poços de Caldas", "Patos de Minas", "Pouso Alegre", "Teófilo Otoni", "Barbacena", "Sabará", "Varginha"], "PA": ["Belém", "Ananindeua", "Santarém", "Marabá", "Parauapebas", "Castanhal", "Abaetetuba", "Cametá", "Marituba", "Bragança", "Altamira", "Tucuruí"], "PB": ["João Pessoa", "Campina Grande", "Santa Rita", "Patos", "Bayeux", "Sousa", "Cajazeiras", "Cabedelo", "Guarabira", "Sapé"], "PR": ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "São José dos Pinhais", "Foz do Iguaçu", "Colombo", "Guarapuava", "Paranaguá", "Araucária", "Toledo", "Apucarana", "Pinhais", "Campo Largo", "Almirante Tamandaré", "Umuarama", "Piraquara", "Cambé", "Fazenda Rio Grande"], "PE": ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru", "Petrolina", "Paulista", "Cabo de Santo Agostinho", "Camaragibe", "Garanhuns", "Vitória de Santo Antão", "Igarassu", "São Lourenço da Mata"], "PI": ["Teresina", "Parnaíba", "Picos", "Piripiri", "Floriano", "Campo Maior", "Barras", "União", "Altos", "Pedro II"], "RJ": ["Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Niterói", "Belford Roxo", "São João de Meriti", "Campos dos Goytacazes", "Petrópolis", "Volta Redonda", "Magé", "Itaboraí", "Macaé", "Mesquita", "Nova Friburgo", "Barra Mansa", "Angra dos Reis", "Nilópolis", "Teresópolis", "Cabo Frio"], "RN": ["Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante", "Macaíba", "Ceará-Mirim", "Caicó", "Açu", "Currais Novos", "João Câmara"], "RS": ["Porto Alegre", "Caxias do Sul", "Canoas", "Pelotas", "Santa Maria", "Gravataí", "Viamão", "Novo Hamburgo", "São Leopoldo", "Rio Grande", "Alvorada", "Passo Fundo", "Sapucaia do Sul", "Uruguaiana", "Santa Cruz do Sul", "Cachoeirinha", "Bagé", "Bento Gonçalves", "Erechim", "Guaíba"], "RO": ["Porto Velho", "Ji-Paraná", "Ariquemes", "Vilhena", "Cacoal", "Rolim de Moura", "Jaru", "Guajará-Mirim", "Pimenta Bueno", "Ouro Preto do Oeste"], "RR": ["Boa Vista", "Rorainópolis", "Caracaraí", "Pacaraima", "Mucajaí", "Cantá", "Alto Alegre"], "SC": ["Florianópolis", "Joinville", "Blumenau", "São José", "Criciúma", "Chapecó", "Itajaí", "Jaraguá do Sul", "Lages", "Palhoça", "Balneário Camboriú", "Brusque", "Tubarão", "São Bento do Sul", "Caçador", "Camboriú", "Navegantes", "Concórdia", "Rio do Sul", "Araranguá"], "SP": ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André", "Osasco", "São José dos Campos", "Ribeirão Preto", "Sorocaba", "Santos", "Mauá", "São José do Rio Preto", "Mogi das Cruzes", "Diadema", "Jundiaí", "Piracicaba", "Carapicuíba", "Bauru", "Itaquaquecetuba", "Franca", "São Vicente", "Praia Grande", "Guarujá", "Taubaté", "Limeira", "Suzano", "Sumaré", "Barueri", "Embu das Artes", "Marília", "Americana", "Indaiatuba", "Araraquara", "Cotia", "Jacareí", "Presidente Prudente", "Hortolândia", "Rio Claro", "Araçatuba", "Catanduva"], "SE": ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana", "São Cristóvão", "Estância", "Tobias Barreto", "Itabaianinha", "Simão Dias", "Nossa Senhora da Glória"], "TO": ["Palmas", "Araguaína", "Gurupi", "Porto Nacional", "Paraíso do Tocantins", "Colinas do Tocantins", "Guaraí", "Tocantinópolis", "Dianópolis", "Formoso do Araguaia"]};
export const GAZ = {
  "curitiba": { n: "Curitiba/PR", c: [-25.43, -49.27] },
  "sao jose dos pinhais": { n: "S. J. dos Pinhais/PR", c: [-25.53, -49.20] },
  "s j dos pinhais": { n: "S. J. dos Pinhais/PR", c: [-25.53, -49.20] },
  "araucaria": { n: "Araucária/PR", c: [-25.59, -49.41] },
  "ponta grossa": { n: "Ponta Grossa/PR", c: [-25.09, -50.16] },
  "londrina": { n: "Londrina/PR", c: [-23.31, -51.16] },
  "maringa": { n: "Maringá/PR", c: [-23.42, -51.93] },
  "cascavel": { n: "Cascavel/PR", c: [-24.95, -53.46] },
  "foz do iguacu": { n: "Foz do Iguaçu/PR", c: [-25.54, -54.58] },
  "guarapuava": { n: "Guarapuava/PR", c: [-25.39, -51.46] },
  "paranagua": { n: "Paranaguá/PR", c: [-25.52, -48.51] },
  "toledo": { n: "Toledo/PR", c: [-24.72, -53.74] },
  "campo mourao": { n: "Campo Mourão/PR", c: [-24.04, -52.38] },
  "pato branco": { n: "Pato Branco/PR", c: [-26.23, -52.67] },
  "francisco beltrao": { n: "Francisco Beltrão/PR", c: [-26.08, -53.05] },
  "telemaco borba": { n: "Telêmaco Borba/PR", c: [-24.32, -50.62] },
  "irati": { n: "Irati/PR", c: [-25.47, -50.65] },
  "uniao da vitoria": { n: "União da Vitória/PR", c: [-26.23, -51.09] },
  "umuarama": { n: "Umuarama/PR", c: [-23.77, -53.32] },
  "joinville": { n: "Joinville/SC", c: [-26.30, -48.85] },
  "florianopolis": { n: "Florianópolis/SC", c: [-27.59, -48.55] },
  "blumenau": { n: "Blumenau/SC", c: [-26.92, -49.07] },
  "itajai": { n: "Itajaí/SC", c: [-26.91, -48.66] },
  "chapeco": { n: "Chapecó/SC", c: [-27.10, -52.62] },
  "lages": { n: "Lages/SC", c: [-27.82, -50.33] },
  "criciuma": { n: "Criciúma/SC", c: [-28.68, -49.37] },
  "sao paulo": { n: "São Paulo/SP", c: [-23.55, -46.63] },
  "campinas": { n: "Campinas/SP", c: [-22.91, -47.06] },
  "sorocaba": { n: "Sorocaba/SP", c: [-23.50, -47.46] },
  "registro": { n: "Registro/SP", c: [-24.49, -47.84] },
  "porto alegre": { n: "Porto Alegre/RS", c: [-30.03, -51.22] },
  "rio de janeiro": { n: "Rio de Janeiro/RJ", c: [-22.91, -43.17] },
  "belo horizonte": { n: "Belo Horizonte/MG", c: [-19.92, -43.94] },
  "fazenda rio grande": { n: "Fazenda Rio Grande/PR", c: [-25.66, -49.31] },
  "colombo": { n: "Colombo/PR", c: [-25.29, -49.22] },
  "pinhais": { n: "Pinhais/PR", c: [-25.44, -49.19] },
  "ipatinga": { n: "Ipatinga/MG", c: [-19.47, -42.54] },
  "ipatinga mg": { n: "Ipatinga/MG", c: [-19.47, -42.54] },
  "sao bernardo do campo": { n: "S. Bernardo do Campo/SP", c: [-23.69, -46.56] },
  "sao caetano do sul": { n: "S. Caetano do Sul/SP", c: [-23.62, -46.55] },
  "santo andre": { n: "Santo André/SP", c: [-23.66, -46.53] },
  "cubatao": { n: "Cubatão/SP", c: [-23.89, -46.43] },
  "santos": { n: "Santos/SP", c: [-23.96, -46.33] },
  "bertioga": { n: "Bertioga/SP", c: [-23.85, -46.14] },
  "sao jose dos campos": { n: "S. José dos Campos/SP", c: [-23.18, -45.88] },
  "taubate": { n: "Taubaté/SP", c: [-23.03, -45.55] },
  "itapevi": { n: "Itapevi/SP", c: [-23.55, -46.93] },
  "paulinia": { n: "Paulínia/SP", c: [-22.76, -47.15] },
  "guarulhos": { n: "Guarulhos/SP", c: [-23.45, -46.53] },
  "osasco": { n: "Osasco/SP", c: [-23.53, -46.79] },
  "barra mansa": { n: "Barra Mansa/RJ", c: [-22.54, -44.17] },
  "volta redonda": { n: "Volta Redonda/RJ", c: [-22.52, -44.10] },
  "duque de caxias": { n: "Duque de Caxias/RJ", c: [-22.79, -43.31] },
  "rio grande": { n: "Rio Grande/RS", c: [-32.04, -52.10] },
  "canoas": { n: "Canoas/RS", c: [-29.92, -51.18] },
  "caxias do sul": { n: "Caxias do Sul/RS", c: [-29.17, -51.18] },
  "camacari": { n: "Camaçari/BA", c: [-12.70, -38.32] },
  "salvador": { n: "Salvador/BA", c: [-12.97, -38.50] },
  "betim": { n: "Betim/MG", c: [-19.97, -44.20] },
  "contagem": { n: "Contagem/MG", c: [-19.93, -44.05] },
};
export const MATRIZ_GEO = { n: "Curitiba (Matriz)", c: [-25.43, -49.27] };
export const FONTES_LOCAL = ["Ponto eletrônico", "GPS veículo", "Manual"];
export const REGIOES_BASE = ["Curitiba (Matriz)","Região Metropolitana de Curitiba","Interior PR","Santa Catarina","São Paulo","Outros estados"];
