export const STATUS_TAP = ["Aguardando Plano de Trabalho", "Plano de Trabalho recebido", "Pré-agendado", "Em campo", "Concluído", "Cancelado"];
export const TAP_MAPA = [
  ["idgeo", "idgeo"],
  ["nome do projeto", "projeto"],
  ["carteira", "carteira"],
  ["e mail do gerente", "gerenteEmail"],
  ["gerente do projeto", "gerente"],
  ["nome do cliente", "cliente"],
  ["cnpj do cliente", "cnpj"],
  ["cidade", "cidade"],
  ["contato do cliente", "contato"],
  ["valor do contrato", "valor"],
  ["margem de lucro", "margem"],
  ["data criacao", "dataCriacao"],
  ["data de entrada em campo", "entradaCampo"],
  ["prazo de mobilizacao", "mobilizacao"],
  ["entrega de relatorio", "entregaRelatorio"],
  ["agendamento de integracao", "prazoIntegracao"],
  ["envio das documentacoes", "prazoDocsMob"],
  ["plano de trabalho", "prazoPlanoTrab"],
  ["data do kickoff", "kickoff"],
  ["menor que 15 dias", "urgente15"],
  ["expectativa de prazo", "expectativa"],
  ["riscos do projeto", "riscos"],
  ["restricoes do projeto", "restricoes"],
  ["premissas operacionais", "premOper"],
  ["premissas tecnicas", "premTec"],
  ["premissas estabelecidas", "premNeg"],
  ["premissas estrategicas", "premEstr"],
  ["expectativa de metas", "metas"],
  ["atendimentos urgentes", "urgencias"],
  ["riscos de multas", "multas"],
  ["autor", "autor"],
];
export const PRIORIDADES = ["Alta", "Média", "Baixa"];
